version: "3"
services:
  postgres:
    image: postgres:10.7-alpine
    environment:
      - POSTGRES_PASSWORD=password
  ftp:
    image: cumuluss/vsftpd:3
    network_mode: "service:build_env"
    volumes:
      - ../packages/test-data:/srv:ro
    environment:
      - FTP_USER=testuser
      - FTP_PASSWORD=testpass
      - FTP_PASV_ADDRESS=127.0.0.1
  http:
    image: httpd:alpine
    network_mode: "service:build_env"
    volumes:
      - ../packages/test-data:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  sftp:
    image: nsidc/panubo_sshd:latest
    command: /bootstrap-sftp.sh
    network_mode: "service:build_env"
    volumes:
      - ./bootstrap-sftp.sh:/bootstrap-sftp.sh
      - ../packages/test-data/keys/ssh_client_rsa_key.pub:/etc/authorized_keys/user
      - ../packages/test-data:/data_volume
      # WARNING - the following mount will have all data wiped each time the stack is
      # brought up via ./bootstrap-sftp.sh.   Think twice before changing this.
      - /tmp/cumulus_unit_test_data:/data
    environment:
      - SSH_USERS
      - SFTP_MODE=true
      - CI=true
  elasticsearch:
    image: elasticsearch:5.6
    network_mode: "service:build_env"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  localstack:
    image: localstack/localstack:0.10.7
    network_mode: "service:build_env"
    environment:
      SERVICES: "cloudformation,cloudwatch,cloudwatchlogs,dynamodb,kinesis,kms,lambda,s3,secretsmanager,sns,sqs,stepfunctions"
  build_env:
    image: maven.earthdata.nasa.gov/cumulus:latest
    volumes:
      - ../:/source/cumulus
      - /tmp/cumulus_unit_test_data:/tmp/cumulus_unit_test_data
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - LOCAL_ES_HOST=127.0.0.1
      - CI_UID
      - DOCKER_TEST_RUN=true
      - bamboo_planKey
    command: tail -f /dev/null
